### ISSUE TITLE
RFC: update resource management in Kata

### ISSUE THREAD

**Issue by egernst** [kata-containers/runtime#1535]
## Upate Resource Management in Kata

There are gaps and issues around our cgroup / resource management utilization in Kata.  This is a meta issue to cover some of the work items.

There are a few PRs in flight around cgroup fixing, and I'd like to get the design and work tracked.  To this end, I'm creating a PR with a design.md, to facilitate comments/discussion around design.  We can discuss in an AC call aftr folks have enough time to review.  Once completed, we can move the resulting doc to the documentation repository.

I ceated and am using the GitHub Milestone "cgroup-sprint" for this work. I'd really like to see this resolved for 1.7-rc0 release, which is in 3 weeks.  Let's see what we can do.

## Work Items: 
 - [x] - agree to design proposal.  See https://github.com/kata-containers/documentation/pull/428
 - [x] - don't confuse CAdvisor by creating cgroups on host with container ID in the kubepod. See https://github.com/kata-containers/runtime/pull/1518
 - [x] - guarantee `guaranteed` performance when using guaranteed QoS
 - [ ] - Better handling of unbound burstable pods.  See https://github.com/kata-containers/runtime/issues/1534
