### ISSUE TITLE
clh: Summarize and track the status of cloud-hypervisor integration

### ISSUE THREAD

**Issue by likebreath** [kata-containers/runtime#2545]
This issue provides an overview of the process to finish the [cloud-hypervisor](https://github.com/cloud-hypervisor/cloud-hypervisor) (`clh`) integration in Kata, and helps to track the integration progress. It also provides a common place for developers to share thoughts and give feedback. What's more, for detailed issues/PRs related to the integration, please check this `project`: https://github.com/orgs/kata-containers/projects/21.

The integration process are divided into the following categories (which can be interdependent):

* Complete the implementation for the `Hypervisor` interface functions
   * __Target__: Provide complete and seamless support of `clh` in Kata by following Kata's `Hypervisor` interface specification.
   * __Status__: All core functionalities are covered, along with few improvements working-in-progress. Also, some of the APIs are not needed for now (mainly legacy). Note kata 2.0 is on parity with kata 1.x (https://github.com/kata-containers/kata-containers/issues/461). Details are tracked here #2544. 
* Pass all (applicable) integration tests (on Docker and Kubernetes) and extend  CI coverage
   * __Target__: Stabilize the implementation and assure high confidence to use `clh` in Kata.
   * __Status__: All k8s test is passing and one test on docker is skipped. Details are tracked here https://github.com/kata-containers/tests/issues/2399. Comprehensive CI coverage for kata 1.x (details in this [Wiki page](https://github.com/kata-containers/ci/wiki/cloud-hypervisor)), including `functional/minmal`, `docker`, `k8s-containerd`, `k8s-e2e` (both crio and containerd), `podman`, `vfio`, and `metrics`. Major outstanding items are: 1) debug and fix known issues (listed [here](https://github.com/orgs/kata-containers/projects/21#column-11137804)); 2) extend our CI coverage for kata 2.0, where we are only covering `k8s+containerd` (https://github.com/kata-containers/ci/issues/345).
* Enable applicable `clh` features
  * __Target__: Bring all (applicable) features of `clh` to Kata to boost performance/security.
  * __Status__: The support for `clh` REST APIs are mostly done with more features are working-in-progress, such as: 
     * [ ] Status of REST APIs usage: #2541 
     * [x] VFIO support: #2519 
     * [x] Use pmem (w/ read-only) to boot kata image: to-be-added
     * [x] Enable block device hotplug #2570 
     * [ ] Use virtio-mem as experimental feature #2568 
     * [x] SGX support (https://github.com/kata-containers/kata-containers/pull/484)
     * [ ] Enable the seccomp enforcement for all worker threads in clh (#2901)

* Misc: the following are few related topics (lower-priority in general)
   * [x] Rust agent: https://github.com/kata-containers/osbuilder/pull/361
   More tests and other corner case tests require manual validation
      * [ ] increase unit tests for `clh` implementation up to 80%
      * [x] k8s end-to-end test in Kata #2570 https://github.com/kata-containers/tests/issues/2417,    
   * [ ] Guest kernel: now using experimental kernel with several patches
   * [ ] Packaging and configuration
   * [ ] Rootless hypervisor

Note: @jcvenegas is the main contributor behind this integration effort. @ericooper introduced the the initial support of `clh` in Kata with #2164. @sboeuf is our `clh` consultant on-demand and guided us to fix the notorious test failure (https://github.com/kata-containers/tests/issues/2141). Of course, the integration process won't be possible without numerous code reviews and bug fixings offered by many Kata developers.

See the complete list of [missing items](https://github.com/issues?q=is%3Aopen+is%3Aissue++archived%3Afalse+user%3Akata-containers+project%3Akata-containers%2F21+)

**Comment by amshinde** [comment]
@likebreath I would also add support for block devices to the list. This would be helpful un supporting persistent volumes in k8s that are backed by block devices.

**Comment by sboeuf** [comment]
FYI, Cloud-Hypervisor supports `virtio-blk`, and we just added the support for hotplugging block devices. So I think this should be able to cover the use case with volumes.

**Comment by likebreath** [comment]
@amshinde @jcvenegas I just updated this mega issue (summary) and also its sub-issues. Please feel free to make changes as you find necessary. Any questions or comments, please let me know. Thanks.

**Comment by jodh-intel** [comment]
@likebreath - should this be release-gating (for 2.0)?

**Comment by likebreath** [comment]
@jodh-intel I don't think so, given major missing items are mostly for improvements, e.g. fixing enabling the skipped k8s/docker tests and extending CI coverage (mainly in kata 2.0), etc. wdyt? @amshinde @jcvenegas

**Comment by fidencio** [comment]
---

This issue is being automatically closed as Kata Containers 1.x has now reached EOL (End of Life). This means it is **no longer being maintained**.

> **Important:**
>
> All users should switch to the latest [Kata Containers 2.x release](https://github.com/kata-containers/kata-containers/blob/main/docs/install/README.md) to ensure they are using a maintained release that contains the latest security fixes, performance improvements and new features.

This decision was discussed by the @kata-containers/architecture-committee and has been announced via the [Kata Containers mailing list](http://lists.katacontainers.io/pipermail/kata-dev/):
* http://lists.katacontainers.io/pipermail/kata-dev/2020-November/001601.html
* http://lists.katacontainers.io/pipermail/kata-dev/2021-April/001843.html
* http://lists.katacontainers.io/pipermail/kata-dev/2021-May/001896.html

If you believe this issue still applies to Kata Containers 2.x, please open an issue against the [Kata Containers 2.x repository](https://github.com/kata-containers/kata-containers), pointing to this one, providing details to allow us to migrate it.

---
